# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b1cc7a61d2957df2a6885b5257fc5dd1f51cc59c3c8a3c9dee80ea309c3b60a076c3183345b97a96d5bcbe817e3841d01c968a7c3924513d8cea7fa0bfa900e7

test:
  secret_key_base: 8882e259b5fe6f34b40e3253012aba2d34dcd4abcb310c5d4a25b0276ee42befda5e62e63ef76dc3ebb7c52f6af64472719a5f3c51ee35fc3d20b50853458b80

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
